Uploading all REST APIs
KITKryptoDAO/NoFraudToken pull request #5
Opened 2023-12-04 17:50 UTC by AtmanDai

Here are 6 REST APIs that contain all the functions the frontend may need. The frontend can choose the APIs that it needs. Following are some descriptions of the functions of respective APIs.

pinAuthen.py is designed to authenticate API keys and the ability to connect to the Pinata API. JWT is the secret access token to our dedicated gateway and an encoded mix of secret and public API keys.

pinJSON.py is designed to upload JSON objects obtained from Frontend to Pinata and pin it to IPFS. We temporarily set the key-values pairs in the Metadata of our JSON objects to contract address/contract_addr to record the contract address of the fraud NFTs. This can be changed according to the demands.

pinByCID.py is designed to pin objects already existing in other IPFS nodes by providing their CIDs.

updateMetadata.py is designed to change the name and custom key-values associated with a piece of content stored on Pinata.

listFiles.py is designed to query files stored on Pinata by their metadata.

delete.py is designed to Delete a file by CID.

Feel free to contact me if you have questions or find some issues.

2023-12-04 19:12 UTC, hannesgao commented
@AtmanDai Hi, have you tested with [postman](https://www.postman.com/) that the REST APIs works?

2023-12-04 19:18 UTC, AtmanDai commented
> @AtmanDai Hi, have you tested with [postman](https://www.postman.com/) that the REST APIs works?

Not yet. I will do it right now.

2023-12-04 19:51 UTC, AtmanDai commented
> @AtmanDai Hi, have you tested with [postman](https://www.postman.com/) that the REST APIs works?

well, actually, I have tested them in my local workspace, shall I test them again with Postman?

2023-12-04 20:06 UTC, AtmanDai commented
@hannesgao Now I have tested all of them with Postman, and they all work well. Actually, I have tested them in my local workspace before Push, but never mind, Postman is more efficient.

2023-12-04 20:09 UTC, niemand-01 commented
If I understand it correctly, we want a function written in JS that can be called by frontend? So the CRUD should be written in js instead of py? @hannesgao

2023-12-04 20:58 UTC, hannesgao commented
> If I understand it correctly, we want a function written in JS that can be called by frontend? So the CRUD should be written in js instead of py? @hannesgao

As long as there is APIs available for deployment (such as these currently written by @AtmanDai in Python), the front-end can use Axios to make API Calls to interact with the back-end API, but then it becomes a Client-Server structure.

What we may eventually want to achieve is a Serverless structure, meaning that all the interaction with IPFS and the backend is performed and implemented on the front-end, which means that subsequent iterations may need to rewrite this part of the API into a JS version that runs in the browser and integrates with the front-end.

In the demo version, we can use the Python backend API for deployment, and rewrite its service logic into a JS version in subsequent iterations after the hackathon.

2023-12-04 21:07 UTC, hannesgao commented
@niemand-01 Please take some time to review the code by @AtmanDai today or tomorrow and if there are no issues and works well please pass and merge the PR, thanks! If there's anything else not clear, feel free to ask here.

2023-12-04 21:58 UTC, niemand-01 commented
Hi @hannesgao,

Thanks for the heads-up. I guess it's because I'm not part of the discussion that U want to revert back to python version as backend, which is an idea at the initial stage, but u abolished it for concern that we need to use more distributed technologies for data storage and create lightweighted backend. Nonetheless, it's also ok to use py if there's no problem for frontend to interact. I will review this PR tmrw, by then @AtmanDai can work with you to test the integration with frontend.

Regards,

2023-12-05 19:46 UTC, niemand-01 requested changes
Hi @AtmanDai,

I will propose the following changes: 
- We can wrap all the functions in one file called: `ipfs_interaction.py`.
- Move the `JWT` to `.env` and reuse this secret for all functions.
- If we want to use python as script, we can create a new file called `run_database.py`. This script can offer different interface for operations. The interface can be realized via [argparse](https://docs.python.org/3/library/argparse.html). How to implement this, I will leave it to you. One way to invoke this script could be: `python run_databse.py --method delete/pin/list/update`. We could leave `--jwt` as optional with default value from `.env`

Regards,

2023-12-05 19:46 UTC, niemand-01 commented on delete.py
> +        "authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mb3JtYXRpb24iOnsiaWQiOiIyM2IyMWI5YS0wM2JhLTQ3YzItOGVjNC0zOWE0Y2RmNTlhZGUiLCJlbWFpbCI6ImRhaXJ1aXo1MDhAZ21haWwuY29tIiwiZ
Can we move the `JWT` login secret to `.env` file and then we can use [dotenv ](https://pypi.org/project/python-dotenv/)to load the secret?

2023-12-05 19:46 UTC, niemand-01 commented on delete.py
> +CID = "PASTE CID HERE"
Maybe we want to use `argparse` to input CID?

2023-12-05 19:46 UTC, niemand-01 commented on listFiles.py
> +        "authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mb3JtYXRpb24iOnsiaWQiOiIyM2IyMWI5YS0wM2JhLTQ3YzItOGVjNC0zOWE0Y2RmNTlhZGUiLCJlbWFpbCI6ImRhaXJ1aXo1MDhAZ21haWwuY29tIiwiZ
Same as above, so we can reuse the `JWT`.

2023-12-08 10:28 UTC, AtmanDai commented
> Hi @AtmanDai,
> 
> I will propose the following changes:
> 
> * We can wrap all the functions in one file called: `ipfs_interaction.py`.
> * Move the `JWT` to `.env` and reuse this secret for all functions.
> * If we want to use python as script, we can create a new file called `run_database.py`. This script can offer different interface for operations. The interface can be realized via [argparse](https://docs.python.org/3/library/argparse.html). How to implement this, I will leave it to you. One way to invoke this script could be: `python run_databse.py --method delete/pin/list/update`. We could leave `--jwt` as optional with default value from `.env`
> 
> Regards,

Hi @niemand-01 ,

as you suggested before, I encapsulate all functions in run_database.py and move our JWT KEY to .env so that it won't be exposed. Thus, the project can be secure.

Additionally, using argparse is a good choice to interact with scripts, thanks for your suggestion. I added four arguments corresponding to CRUD database options and other arguments to input metadata as required.

If there are other problems, feel free to contact me.

Best Regards,

2023-12-08 18:58 UTC, niemand-01 approved these changes
🐉 @AtmanDai Thanks for the implementation, I think it's good for current need, he also demonstrated the file to me yesterday and it works fine, I guess testing using [unittest](https://docs.python.org/3/library/unittest.html) could be bit overkill fn. wdyt? @hannesgao

2023-12-08 19:41 UTC, hannesgao commented
> 🐉 @AtmanDai Thanks for the implementation, I think it's good for current need, he also demonstrated the file to me yesterday and it works fine, I guess testing using [unittest](https://docs.python.org/3/library/unittest.html) could be bit overkill fn. wdyt? @hannesgao

No need for unit test rn. It's already fine.

2023-12-08 19:41 UTC, merged

2023-12-08 19:42 UTC, hannesgao reviewed
Reviewed and merged to main branch